### PR TITLE
Make main menu scrollable.

### LINKED ISSUE #1781: Make main menu scrollable
As we are adding more entries to the main menu, if they're all enabled they may not all be accessible on a small screen (e.g. landscape on a smartphone). The main menu needs to be scrollable to reach the later entries.

### PR DESCRIPTION
**Pull request by mrstegeman**
Fixes #1781

### CODE REVIEW

**Comment by hobinjk** [comment]
It would be nice to have a conditional border or drop-shadow on the bottom of the wordmark section so that the scrolling area is better distinguished. Otherwise it's just

**Comment by benfrancis** [comment]
> It would be nice to have a conditional border or drop-shadow on the bottom of the wordmark section so that the scrolling area is better distinguished.

Oh sorry, I didn't spot this. Good point. Not actually sure how to fix this without re-designing the menu. Maybe a follow-up task? (At least it's now useable).

**Comment by hobinjk** [comment]
Yeah, it's definitely good enough as-is and the bar does go a ways to setting off the scrollable vs non-scrollable content

**Comment by mrstegeman** [comment]
@benfrancis @hobinjk Let me know what you think about the border I just added. I can back it out if you dislike.

**Comment by hobinjk** [comment]
:+1: LGTM

**Comment by benfrancis** [comment]
Thanks for trying that but honestly I think it looks better without.

@hobinjk's idea of a dropshadow might work better but would need applying to the top element.

Honestly, it's probably fine as it was for now as this is an edge case.

**Pull request merged**
