### PR TITLE
Update default dnsmasq configuration.

### PR DESCRIPTION
**Pull request by mrstegeman**

### CODE REVIEW

**Comment by mrstegeman** [comment]
@dhylands Should we also update the config to serve DHCP on eth0?

**Comment by dhylands** [comment]
Which router are we talking about? This looks like the captive portal IP address. For captive portal I think we should only run the DHCP server on wifi. It probably makes sense to run DHCP client on any LAN ports.

I know on my RPi, I often connect to LAN and setup the WiFi SSID/password over the LAN connection because my desktop doesn't have WiFi

**Comment by mrstegeman** [comment]
I think we'll only ever want to run the DHCP server on the wifi network, given that there's just a single ethernet port. It doesn't make a lot of sense to run it on eth0 as well.

**Comment by dhylands** [comment]
I think once things are setup, if you're running like a "normal" router, i.e. internet access comes in through the WAN port, then you definitely want to run the DHCP server for both WiFi and LAN ports.

If the internet comes through WiFi or LAN, then we wouldn't want to run a DHCP server.

**Pull request merged**
