### PR TITLE
Refine color light icon view

### LINKED ISSUE #572: Proposed refinements to color light thing icons
Seeing the color light thing types implemented and used alongside other things types, I'm finding the visual design a bit jarring.

Here is a proposed alternative design where:
- The background color of the circle is always blue when off and white when on, which makes it more consistent with other web thing types and makes it easier to tell at a glance whether lights are on or off
- The background color of the bulb changes based on the color of the light, rather than the background color of the circle. This has the advantage that you can tell what color the bulb is set to when it's off.
- The border color is set to #fff or #666 depending on the intensity of the color of the bulb

coloured_dimmable_bulb-off2

dimmable-color-light-on2

coloured_dimmable_bulb-off-green2

dimmable-color-light-on-green

things-off-2

things2

### PR DESCRIPTION
**Pull request by hobinjk**
Close #572

### CODE REVIEW

**Comment by hobinjk** [comment]
@benfrancis I made the on/off/level text grey but I can also make it blue if you'd prefer (the mockups had both, seemingly dependent on whether the color is bright)

**Comment by hobinjk** [comment]
I'm going to make it blue for now

**Comment by benfrancis** [comment]
Oh yeah sorry, it was meant to be blue :)

**Comment by hobinjk** [comment]
\o/

**Pull request merged**
