### PR TITLE
New serialport

### PR DESCRIPTION
**Pull request by dhylands**

### CODE REVIEW

**Comment by hobinjk** [comment]
I'm testing this locally and it LGTM so far, thanks!

**Comment by dhylands** [comment]
ZWave doesn't seem to be working under OSX. Investigating. ZigBee seems to work fine.

**Comment by dhylands** [comment]
Seems to be related to the difference between /dev/cu.usbmodemXXX and /dev/tty.usbmodemXXX

**Comment by dhylands** [comment]
ZigBee and ZWave now work properly under OSX. - so this should be good to go now.

**Pull request merged**
