### PR TITLE
Implement back-end for platform settings.

### PR DESCRIPTION
**Pull request by mrstegeman**
References #216
References #217
References #909

### CODE REVIEW

**Comment by jaller94** [comment]
@mrstegeman Has this feature been until in 0.5.2? I still see it in the code but I fail to find it in the web interface of my gateway.
Does it need to be activated?

**Comment by mrstegeman** [comment]
@jaller94 This commit should be in all 0.5.X versions. It's accessed via _Settings->Developer_. Most things are only available on the Raspberry Pi for now.

**Comment by mrstegeman** [comment]
Yep, that sound right. Are you looking for another setting in particular?

**Comment by mrstegeman** [comment]
Nope, not yet. We haven't enabled that from the UI yet (#217). It can be done via the [API](https://github.com/mozilla-iot/gateway/blob/master/src/controllers/settings_controller.js#L393), though.

**Pull request merged**
