### PR TITLE
Add Russian translation

### PR DESCRIPTION
**Pull request by wtigga**
Russian locale file based off English locale from 2019-11-22, tb updated after the initial release.

### CODE REVIEW

**Comment by mrstegeman** [comment]
Please also update `l10n.toml` and `static/js/fluent.js`.

**Comment by kgiori** [comment]
Just a couple notes.
Lines 299-335 (time phrases) -- can they be translated?
Lines 522-539 -- some english phrases in there (continuation lines) to be deleted or translated?

**Comment by wtigga** [comment]
> 
> 
> Just a couple notes.
> Lines 299-335 (time phrases) -- can they be translated?
> Lines 522-539 -- some english phrases in there (continuation lines) to be deleted or translated?

Whoops that slipped through OmegaT filter somehow, will fix that.

**Comment by mrstegeman** [comment]
@wtigga Please also update `l10n.toml` and `static/js/fluent.js`.

**Comment by wtigga** [comment]
> 
> 
> @wtigga Please also update `l10n.toml` and `static/js/fluent.js`.

done

**Comment by mrstegeman** [comment]
@wtigga you can now find this project in Pontoon: https://pontoon.mozilla.org/projects/webthings-gateway/

**Comment by wtigga** [comment]
> 
> 
> @wtigga you can now find this project in Pontoon: https://pontoon.mozilla.org/projects/webthings-gateway/

Nice! One more step for the global expansion of the Gateway.
I only wish those previously translated stats appeared on my Pontoon profile :-)

**Comment by wtigga** [comment]
How does one acquire the "Translator" status on the project in Pontoon by the way?

**Comment by mrstegeman** [comment]
> How does one acquire the "Translator" status on the project in Pontoon by the way?

@flodolo and @peiying2 would know better than me, as I'm brand new to Pontoon.

**Comment by peiying2** [comment]
> How does one acquire the "Translator" status on the project in Pontoon by the way?

@wtigga Have you set up an account in Pontoon yet? Basically the locale managers will review your work and decide if you can be promoted to the Translator level. All new contributors start off as Contributor which means his/her work needs review before the string is accepted to be used on production. Since your work is synced up through GitHub, it is automatically accepted. Here is the Pontoon user guide: https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/index.html.

Let me know if you would like me to introduce you to the Russian community managers.

**Comment by wtigga** [comment]
> 
> 
> > How does one acquire the "Translator" status on the project in Pontoon by the way?
> 
> @wtigga Have you set up an account in Pontoon yet? Basically the locale managers will review your work and decide if you can be promoted to the Translator level. All new contributors start off as Contributor which means his/her work needs review before the string is accepted to be used on production. Since your work is synced up through GitHub, it is automatically accepted. Here is the Pontoon user guide: https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/index.html.
> 
> Let me know if you would like me to introduce you to the Russian community managers.

Yes, I have Pontoon profile and have already contributed a hundred or two strings into Mozilla projects. I'd be delighted if you can introduce me to the Russian community manager.

**Comment by peiying2** [comment]
@wtigga are you Vladminer Zh... in Pontoon? I can send an intro

**Comment by wtigga** [comment]
> 
> 
> @wtigga are you Vladminer Zh... in Pontoon? I can send an intro

[Vladimir Zh](https://pontoon.mozilla.org/contributors/mQc3gs_mzJaaZGm8_mOld00-obY/), that's me :-)

**Pull request merged**
