### PR TITLE
Expose add-on licenses in UI.

### LINKED ISSUE #1274: Expose adapter licenses
Adapters are likely using third party libraries or are open source themselves. It would be nice if their licenses were accessible in the UI somehow. Probably with a simple license link in the add-on entry.

I'd suggest that it would just link to the `LICENSE.*` file in the root directory of the adapter if any exists. This means concating the license is up to the maintainer, but should be fairly language agnostic.

### PR DESCRIPTION
**Pull request by mrstegeman**
Depends on mozilla-iot/addon-list#171
Depends on mozilla-iot/addon-proxy#4
Fixes #1274

### CODE REVIEW

**Comment by mrstegeman** [comment]
I was also unsure about this.

@benfrancis any better ideas?

**Comment by mrstegeman** [comment]
screenshot_2019-01-03 things gateway

**Comment by benfrancis** [comment]
Could just remove the words "subject to" and perhaps put the link after the author's name? e.g.

by Martin Giger (license)

**Comment by mrstegeman** [comment]
@benfrancis Done.

screenshot_2019-01-09 things gateway

**Pull request merged**
