### PR TITLE
Implement property web components.

### LINKED ISSUE #1073: OnOffProperty
As a developer I want the gateway UI to show an on/off switch for my device so that it can be turned on and off.

Thing Description example:
```
{
  "name": "My Thing",
  "@context": "https://iot.mozilla.org/schemas",
  "properties": {
    "on1": {
      "name": "On/Off 1",
      "@type": "OnOffProperty",
      "type": "boolean"
    },
    "on2": {
      "name": "On/Off 2",
      "@type": "OnOffProperty",
      "type": "boolean"
    }
  }
}
```

UI mockup:
onoffproperty

### LINKED ISSUE #1074: BrightnessProperty
As a developer I want the gateway UI to show a slider for my device so the user can adjust its brightness.

Thing Description example:
```
{
  "name": "My Thing",
  "@context": "https://iot.mozilla.org/schemas",
  "properties": {
    "brightness": {
      "name": "Brightness",
      "@type": "BrightnessProperty",
      "type": "number",
      "minimum": "0",
      "maximum": "100",
      "unit": "percent"
    }
  }
}
```
UI mockup:
brightnessproperty

### LINKED ISSUE #1075: ColorProperty
As a developer I want the gateway UI to show a colour picker for my device so the user can adjust its colour.

Thing Description example:
```
{
  "name": "My Thing",
  "@context": "https://iot.mozilla.org/schemas",
  "properties": {
    "color": {
      "name": "Color",
      "@type": "ColorProperty",
      "type": "string"
    }
  }
}
```

UI Mockup:
colorproperty

### LINKED ISSUE #1076: InstantaneousPowerProperty
As a developer I want the gateway UI to show the current power consumption of my device so the user knows how much power it's using.

Thing Description example:
```
{
  "name": "My Thing",
  "@context": "https://iot.mozilla.org/schemas",
  "properties": {
    "power": {
      "name": "Power",
      "@type": "InstantaneousPowerProperty",
      "type": "number",
      "unit": "watt"
    }
  }
}
```

UI Mockup:
instantaneouspowerproperty

### LINKED ISSUE #1077: CurrentProperty
As a developer I want the gateway UI to show the current current being drawn by my device.

Thing Description example:
```
{
  "name": "My Thing",
  "@context": "https://iot.mozilla.org/schemas",
  "properties": {
    "current": {
      "name": "Current",
      "@type": "CurrentProperty",
      "type": "number",
      "unit": "ampere"
    }
  }
}
```

UI mockup:
currentproperty

### LINKED ISSUE #1078: VoltageProperty
As a developer I want the gateway UI to show the current voltage being used by my device.

Thing Description example:
```
{
  "name": "My Thing",
  "@context": "https://iot.mozilla.org/schemas",
  "properties": {
    "voltage": {
      "name": "Voltage",
      "@type": "VoltageProperty",
      "type": "number",
      "unit": "voltage"
    }
  }
}
```

UI mockup:
voltageproperty

### LINKED ISSUE #1079: FrequencyProperty
As a developer I want the gateway UI to show the current frequency being used by my device.

Thing Description example:
```
{
  "name": "My Thing",
  "@context": "https://iot.mozilla.org/schemas",
  "properties": {
    "frequency": {
      "name": "Frequency",
      "@type": "FrequencyProperty",
      "type": "number",
      "unit": "hertz"
    }
  }
}
```

UI mockup:
frequencyproperty

### LINKED ISSUE #1080: LevelProperty
As a developer I want the gateway UI to show a graphical representation of the level of my device, or a slider to set the level of my device.

### PR DESCRIPTION
**Pull request by mrstegeman**
Fixes #1073 
Fixes #1074 
Fixes #1075 
Fixes #1076 
Fixes #1077 
Fixes #1078 
Fixes #1079 
Fixes #1080

### CODE REVIEW

**Comment by hobinjk** [comment]
This is a great start! I think we should meet at all-hands to go over the structure we want to use in webcomponents. In this case, I think a lot of the implementation of OnOffProperty would be great to have in a base Property class. While I only have in-depth experience using Polymer, I agree that webcomponentsjs is better than it and other polyfills.

**Comment by mrstegeman** [comment]
@hobinjk Yes, we should definitely discuss. I wanted to get a simple one put together that we could start with, at least. webcomponentsjs did seem to be the most straightforward polyfill to use.

**Comment by mrstegeman** [comment]
@hobinjk @benfrancis I should be done pushing to this PR now.

**Comment by benfrancis** [comment]
@mrstegeman This is so cool.

What's the best way to test it out?

**Comment by benfrancis** [comment]
Actually, scratch that question. I see that most of these components are now used by the existing web thing types so can be tested using the virtual things adapter.

So this pull request doesn't include parsing the `@type`s of properties yet, it just converts the current UI elements into web components using the existing web thing types system?

**Comment by mrstegeman** [comment]
@benfrancis That's correct, it's just the web components for now. I'm going to do the capabilities after this, and then parsing out the `@type` field.

**Comment by mrstegeman** [comment]
@hobinjk Talk to @benfrancis about it 😄 

https://github.com/mozilla-iot/gateway/issues/1080

**Comment by mrstegeman** [comment]
@hobinjk Brightness is #1074

**Comment by hobinjk** [comment]
Okay, I approve of this then. My only suggestion would be to remove the up and down arrow buttons from the number input on the level since those are redundant and not included in the spec.

**Pull request merged**
