### PR TITLE
Implement assistant interface (sans speech).

### LINKED ISSUE #951: Smart Assistant - Written Command & Response
As a user I want to be able to type commands and receive a written response so I don't disturb people nearby

The user can enter natural language commands by typing into a text box and receive a written response.

The icon of the device the command refers to is displayed in the response (e.g. smart plug or light).

### LINKED ISSUE #953: Smart Assistant - Turn devices on and off
As a user I want to turn devices on and off with natural language commands

- Turn \<device name\> \<on|off\>
- Turn the \<device name\> \<on|off\>
- Turn <on|off> \<device name\>
- Turn \<on|off\> the \<device name\>
- Turn the lights \<on|off\>

### LINKED ISSUE #954: Smart Assistant - Set Level
As a user I want to set the level of dimmable lights and level switches with natural language commands

- Set (the) \<device name\> to \<number\> percent
- Dim (the) \<device name\>
- Brighten (the) \<device name\>
- Dim the lights
- Brighten the lights
- Dim (the) \<device name\> by \<number\> percent
- Brighten (the) \<device name\> by \<number\> percent
- Dim the lights by \<number\> percent
- Brighten the lights by \<number\> percent

### LINKED ISSUE #955: Smart Assistant - Set Colour
As a user I want to set the colour of a light using natural language commands

- Turn (the) \<light name\> \<color\>

### LINKED ISSUE #956: Smart Assistant - Set Colour Temperature
As a user I want to set the colour temperature of a light using natural language commands

- Make (the) \<light name\> warmer
- Make the \<light name\> cooler

### LINKED ISSUE #957: Smart Assistant - Clear Conversation History
As a user I want to clear the conversation history with my assistant so that other people can't see it

As commands are issued, a command history builds up and is scrollable.

The command history can be cleared by tapping on the fox avatar.

### LINKED ISSUE #959: Smart Assistant - Sorry, I didn't understand.
When a human says something the assistant doesn’t understand, it politely explain that it doesn’t understand.

### PR DESCRIPTION
**Pull request by mrstegeman**
Fixes #951
Fixes #953
Fixes #954
Fixes #955
Fixes #956
Fixes #957
Fixes #959

### CODE REVIEW

**Comment by benfrancis** [comment]
This is really cool, great progress.

Doing some initial testing, I noticed that the following group of commands don't work yet:
- Turn the lights <on|off>
- Dim the lights
- Brighten the lights
- Dim the lights by <number> percent
- Brighten the lights by <number> percent

I realise this is tricky because it involves searching for all devices with the Light capability (and an OnOffProperty). Being able to do this would be a cool demonstration of the capabilities system though. Do you want to file a follow-up to address this if we can?

I should really have put dimensions and color codes in the UX spec and I'm happy to fix some of the CSS niggles myself if a follow-up if you prefer, but a few things I noticed:
- The left flick on the speech bubbles disappears on screens below about 1024 pixels wide.
- The `#assistant-content` div is a bit too far to the left which throws everything off
- The command input is a bit big bit wide, should be about 32remx3.2rem
- Unfocused state of the input box should have a background-color of #7dafd2 and no submit button
- The avatar image seems to end up a bit high up on the screenfoo
- Speech bubbles should have a width of about 24rem excluding the `::after` flick

There are no images in the speech bubbles to show device type as in the spec, but to be fair I didn't provide any. Happy to address this in a follow-up as it's a fairly minor detail.

I haven't quite finished reviewing the code yet but I need to dash to a meeting so thought I'd leave this here first.

**Comment by hobinjk** [comment]
I think a potentially cool effect to have is instead of drawing an icon in the response draw the thing's htmlView to get an interactive webcomponent.

**Comment by mrstegeman** [comment]
@benfrancis I intentionally didn't do the "turn on the lights" type rules, as I don't know how useful it is to turn on every single light. I filed #1191, as I figured that would be much more useful.

**Comment by benfrancis** [comment]
Mike is off for a while so I'll follow up on this on Monday and make some CSS tweaks before landing.

**Comment by hobinjk** [comment]
I can tackle implementing "turn on the lights" as a neat demo of capabilities. I agree that it's mostly useless but something like "turn off everything" could be good for going on vacation. The sheer drama of "turn everything red" is what I'm really targeting.

**Comment by benfrancis** [comment]
> The sheer drama of "turn everything red" is what I'm really targeting.

LOL.

**Comment by benfrancis** [comment]
Superseded by #1197

**Pull request closed without merging**
