### PR TITLE
Add Dutch translation

### PR DESCRIPTION
**Pull request by qistoph**
Hoping this PR is a useful contribution to this awesome project.

As title says, addition of Dutch (NL) translation.

Really looking forward to future developments.

### CODE REVIEW

**Comment by flatsiedatsie** [comment]
Looks good. Maybe some small things:
- Log Retentie Duur -> log bewaar duur?

**Comment by mrstegeman** [comment]
Please rebase on the latest master and check out the changes to the English translation.

**Comment by mrstegeman** [comment]
@qistoph I've rebased for you and cleaned some things up. The only thing left to be done is to update the `utils-X-ago` tags to use CLDR plurals.

**Comment by qistoph** [comment]
@mrstegeman thanks for rebasing. I have updated the utils-X-ago with CLDR plurals.

**Comment by mrstegeman** [comment]
@qistoph @flatsiedatsie you can now find this project in Pontoon: https://pontoon.mozilla.org/projects/webthings-gateway/

**Pull request merged**
