### PR TITLE
Implement actions UI.

### LINKED ISSUE #907: Actions UI
As a user I want to request an action on a thing so I can modify its state or affect a physical change

### PR DESCRIPTION
**Pull request by mrstegeman**
Fixes #907

### CODE REVIEW

**Comment by hobinjk** [comment]
With the single-thing example from webthing-node I'm not seeing an ActionDetail for the fade action

**Comment by mrstegeman** [comment]
I only attached the action details to the `thing` type, since there are no actions defined in the spec for the other thing types. You can change the thing type for the single-thing example from `dimmableLight` to `thing` and it will work.

**Comment by hobinjk** [comment]
Oh right, of course! Tested locally and LGTM

**Comment by mrstegeman** [comment]
@benfrancis Would you mind checking this out? The latest virtual-things-adapter (v0.2.0) has a new thing with actions and events, so you can test with that.

**Comment by benfrancis** [comment]
This looks great!

Seeing this in action, we could do with a bit more user feedback that an action request has been sent. We could start by adding an active state with a different background colour on the action button when you press it:

- `:disabled`: `#79a1bd`
- (normal): `#698ba4`
- `:hover`: `#59768a`
- `:active`: `#496071`

In addition to this, this wasn't in the spec, but I think the action input form should be dismissed when you press the button and it's submitted. The downside is that makes it harder to issue multiple action requests of the same type in a row, but it makes it much more obvious that the action request has been sent and if the action modifies properties you can immediately see the result. If the form just hangs around it looks like nothing happened.

We could go further than that and add a toast, in the same style as the event notifcations, to show that your action request has been submitted. What do you think? (Happy to do that part in a follow-up).

I wonder whether the touch target on the ellipsis (...) could be larger? It's hard to hit on a touchscreen. We could even make the whole bubble a hyperlink, as long as you can still press the button.

I realise the truncation of action names on buttons isn't ideal, I'll think about that.

Do we not have support for a "name" property of properties, actions and events to provide a human readable string (as opposed to the camelCase IDs)? Same for action inputs. If not I can file a follow-up for that (the W3C are currently proposing calling that "label" rather than "name" though.

One small nit: In the back end URL router the URLs are `actions/*` (plural), in the front end URL router they are `/action/*` (singular). Let's make them both plural for consistency.

As some point we may want to make some of this into web components.

**Comment by mrstegeman** [comment]
> This looks great!
> 
> Seeing this in action, we could do with a bit more user feedback that an action request has been sent. We could start by adding an active state with a different background colour on the action button when you press it:
> 
>     :disabled: #79a1bd
>     (normal): #698ba4
>     :hover: #59768a
>     :active: #496071

Done.

> In addition to this, this wasn't in the spec, but I think the action input form should be dismissed when you press the button and it's submitted. The downside is that makes it harder to issue multiple action requests of the same type in a row, but it makes it much more obvious that the action request has been sent and if the action modifies properties you can immediately see the result. If the form just hangs around it looks like nothing happened.

Done.

> We could go further than that and add a toast, in the same style as the event notifcations, to show that your action request has been submitted. What do you think? (Happy to do that part in a follow-up).

Let's do that as a follow up, once I get the toast architecture figured out.

> I wonder whether the touch target on the ellipsis (...) could be larger? It's hard to hit on a touchscreen. We could even make the whole bubble a hyperlink, as long as you can still press the button.

Done.

> I realise the truncation of action names on buttons isn't ideal, I'll think about that.

Yeah, that was my biggest pain point.

> Do we not have support for a "name" property of properties, actions and events to provide a human readable string (as opposed to the camelCase IDs)? Same for action inputs. If not I can file a follow-up for that (the W3C are currently proposing calling that "label" rather than "name" though.

`"name"` is only ever used in the spec for _Thing_.

> One small nit: In the back end URL router the URLs are actions/* (plural), in the front end URL router they are /action/* (singular). Let's make them both plural for consistency.

Done.

> As some point we may want to make some of this into web components.

Definitely.

**Comment by benfrancis** [comment]
> "name" is only ever used in the spec for Thing.

Huh, you're right. I must be getting confused between specifications again. Seems like something I should file an issue for to address.

One last thing, the touch target on the ellipsis is bigger but now appears to be obscuring half of the button so you can accidentally click the ellipsis rather than the button. The touch target should either butt up against the bottom of the button, or extend across the whole bubble with the button as an unobscured island of touch target in the middle! (if that's possible...).

**Comment by mrstegeman** [comment]
@benfrancis Good catch! I left out 1 CSS rule.

**Pull request merged**
