### PR TITLE
Rules MultiTrigger and Pulse/Set Support

### PR DESCRIPTION
**Pull request by hobinjk**
Only creates OR triggers without a UI to change to AND (and other advanced options like set/pulse).

### CODE REVIEW

**Comment by hobinjk** [comment]
This is in a mostly viable state. I'm interested to see what other people think about the drop-down menu styling:
screen shot 2018-06-22 at 14 54 19

**Comment by hobinjk** [comment]
(hilariously enough the baseline of the normal text is aligned with that of the drop-down text but there's an optical illusion going on)

**Comment by hobinjk** [comment]
(forgot to remove WIP from title)

**Comment by benfrancis** [comment]
Text gets a bit crowded, can we make this fit the available space a bit better, maybe by moving the title upwards or extending the box downwards?

screenshot from 2018-06-29 15-36-36

**Comment by benfrancis** [comment]
I think I found a bug. If you drag a device from the left side to the right side, it doesn't remove the "or" statement from the text description.

**Comment by hobinjk** [comment]
Thanks for the review! Comments addressed

**Comment by benfrancis** [comment]
Thanks, I think this is better. I'm still not 100% sure users will understand the difference, but as long as the default makes sense and the option of more flexibility is there, that's a good place to be in. We can test it with users.

A couple of points:
1. I think "if" and "and" rather than "while" and "or" would be better defaults.
2. I noticed that you can't change while/if until you've dragged in a thing, which I expected to be able to do.

This is really unrelated to this pull request, but is there a reason that all the devices have the symbol for a power switch? I assume that the intention of the designer was that the symbol would reflect the type of device. I think we should show the capability icon as in the floorplan, but without the circle outline. Would you like me to generate images for that and maybe do that in a follow-up? The two images on the rule summary card on the main rules screen was probably also meant to reflect the device types, although that's a bit more tricky now you can include more than two devices.

**Comment by hobinjk** [comment]
The current default is equivalent to "while" so I don't think that changing to "if" is a good idea. Switching to "and" is reasonable though. I can track down whatever's not allowing you to pre-select.

Generating images for use as rule icons would be great! Lack of assets is the only reason that every device is an onoffswitch.

**Comment by benfrancis** [comment]
> Generating images for use as rule icons would be great! Lack of assets is the only reason that every device is an onoffswitch.

I filed https://github.com/mozilla-iot/gateway/issues/1155 with some icons :)

**Comment by hobinjk** [comment]
Comments addressed! I'll get to the icons in the future. I also need to remember to add a play button for the rule preview animation

**Comment by hobinjk** [comment]
https://twitter.com/hobinjk/status/1005182266404999174
There isn't a way of triggering this in the UI but the functionality is there

**Comment by hobinjk** [comment]
Thanks! I improved the display of the drag hints to be bolder

**Pull request merged**
