### PR TITLE
Rules Mobile Friendliness

### LINKED ISSUE #323: Rules UI doesn't scale well on mobile
The rules list doesn't really fit on the screen on mobile.

screenshot_20171010-161406

### PR DESCRIPTION
**Pull request by hobinjk**
Improves the scaling of the rules engine on tiny (320 x 480) devices. Fix #323. This is based on #313 because it has all the new class names and widgets

### CODE REVIEW

**Comment by benfrancis** [comment]
@hobinjk When you say "based on", does this require the commits from #313 or can it be landed independently?

**Comment by hobinjk** [comment]
@benfrancis It was originally built on top of #313 but I changed that and it is now completely separate

**Comment by benfrancis** [comment]
Screenshots below.

Portrait:
screenshot_20171012-160859

Landscape:
screenshot_20171012-160904

**Comment by hobinjk** [comment]
Thanks for the feedback! I agree that my approach was a bit too hacky. I've changed this to be a bit cleaner. It no longer adjusts the base font size. Instead, it puts the rules cards into a centered grid which scales well down to around 400px width. On smaller widths the only thing cut off is the enable/disable switch.

I would consider the ideal to be the cards dynamically becoming taller and skinnier while still appearing in a vertical list.

**Comment by hobinjk** [comment]
It now looks like this. The first rule will be cut off on a sufficiently skinny phone (like a pixel), but that isn't a significant problem in my opinion.
screen shot 2017-10-12 at 12 53 20

screen shot 2017-10-12 at 12 53 25

**Comment by benfrancis** [comment]
Yeah this is better, thanks. One slight issue is that with 3 or more cards the + button can obscure the enable/disable switch on the final card and it's impossible to scroll far enough to reach it so you have to try to squeeze the switch between the + button and the bottom of the screen to make it clickable!. Maybe a bit of padding at the bottom would fix that.

**Comment by hobinjk** [comment]
@benfrancis Added padding to the bottom to get them to not overlap

**Comment by benfrancis** [comment]
\o/ LGTM.

**Pull request merged**
