### PR TITLE
Add post-upgrade script

### LINKED ISSUE #632: Add post-update script to OTA
When doing things like migrating to an LTS version of Node or updating the python add-on library we need a function to run arbitrary scripts after the OTA update successfully completes.

Admittedly this is going to make the OTA process much more difficult to reason about since it will lose its ability to guarantee that it can completely revert an update

### PR DESCRIPTION
**Pull request by hobinjk**
Fix #632. Progresses forward on #641 but the zwave issue needs
consideration.

### CODE REVIEW

**Comment by mrstegeman** [comment]
@hobinjk Could you add the following to `post-upgrade.sh`, please?

```bash
# Upgrade gateway-addon Python package
_url="git+https://github.com/mozilla-iot/gateway-addon-python#egg=gateway_addon"
sudo pip2 install -U "$_url"
sudo pip3 install -U"$_url"
```

**Comment by hobinjk** [comment]
@mrstegeman Updated accordingly

**Comment by mrstegeman** [comment]
Thanks! Are we worried about this messing things up if the update is rolled back?

**Comment by hobinjk** [comment]
The node update will cause issues if the update fails. This can be resolved if we want to create an 0.3.2 release with `nvm alias default v7.10.1` in `upgrade-rollback.sh`. I'm not sure if we are that concerned at this stage but we should attempt to limit this script to backwards-compatible changes in the future.

**Comment by hobinjk** [comment]
Oh wait, the rollback script used is actually this one. I'll update accordingly

**Pull request merged**
