### PR TITLE
Fix translation issues with complex concatentations.

### PR DESCRIPTION
**Pull request by mrstegeman**
This fix is only for en-US right now. Translators will need to fix
existing translations.

References #2326

### CODE REVIEW

**Comment by mrstegeman** [comment]
I believe we're ok to merge this right now, as there's no better alternative for our current design.

The Fluent team suggested that we instead redesign this page such that the &lt;select> is pulled out of the middle of the sentence, since the translation could change based on the selected option.

**Comment by benfrancis** [comment]
> The Fluent team suggested that we instead redesign this page such that the <select> is pulled out of the middle of the sentence

I'm not really sure how this would work...

**Comment by benfrancis** [comment]
I'm not really sure how this would work...

**Comment by mrstegeman** [comment]
I think we’d have a normal prompt, and then below the prompt the user could select monitor or monitor and control. Something of that nature.

**Comment by benfrancis** [comment]
Oh, I see.

**Pull request merged**
