### PR TITLE
Drop commands API.

### PR DESCRIPTION
**Pull request by mrstegeman**
This includes the intent server and the API itself.

### CODE REVIEW

**Comment by mrstegeman** [comment]
@tim-hellhake would you mind reviewing?

**Comment by kgiori** [comment]
wait, what? does this mean that the voice controller (using Snips) will no longer work? please don't break that until we have a solid history of an alternative that works just as well.

**Comment by mrstegeman** [comment]
@lissyx and @andrenatal are working to combine their DeepSpeech and Snips add-ons into one, with an option to select which back-end to use. They will pull the intent parsing and such into the add-on. That way, functionality can be added in a much easier fashion. This is similar to how the Voco add-on works.

**Comment by kgiori** [comment]
ah, I see. happy to hear about the collaboration!

**Comment by mrstegeman** [comment]
@andrenatal FYI

**Comment by flatsiedatsie** [comment]
Wait what? Voco no longer works in 0.11??

**Pull request merged**
