### PR TITLE
Switch to eslint from jshint closes #113

### LINKED ISSUE #113: Switch to eslint to jshint
We talked a bit about this... jshint is no longer the "state of the art" and eslint has a number of great features (like auto fixing, plugins, etc... ).

NOTE: I notice mozilla-central has a eslint style plugin (which we may or may not want to follow)

### PR DESCRIPTION
**Pull request by lightsofapollo**
Once I hit a syntax parse error in jshint I was ready to do this ;)

The rules are not as strict as I would like but this gets us passing and we can add many additional rules later (and take advantage of --fix).

@hobinjk r?

### CODE REVIEW

**Comment by hobinjk** [comment]
Actually, I should look into what's going on with the `new` used for side effect places

**Comment by lightsofapollo** [comment]
@hobinjk done ( I think I left one in test/test.js since I am removing that file in another PR)

**Comment by hobinjk** [comment]
There is still one `/* jshint unused:false */` in `static/js/things.js`.

I've also noticed that in some places you're removing the `'use strict';` statements. Is there a reason for this?

**Comment by lightsofapollo** [comment]
@hobinjk "use strict" does exactly nothing when writing ES6 code (i.e. node/v8 using es6 features) (I left them in static/ for now because we don't have any of the usual cross browser tooling up yet).

**Comment by hobinjk** [comment]
@lightsofapollo As far as I can tell enabling strict mode does have effects. The minimal reproducing example I have on Node v8.1.1 is adding the line `x = 12;` to `app.js`, which throws an error only when `'use strict';` is present.

Per the spec ([2015](http://www.ecma-international.org/ecma-262/6.0/#sec-strict-mode-code)/[2018](https://tc39.github.io/ecma262/#sec-strict-mode-code)) strict mode is only entered automatically in class definitions and Modules. Node.js seems to not consider its files to be Modules, so the only place where strict mode is entered is the class bodies. This leaves a large amount of code uncovered by the guarantees of strict mode, even in required files that happen to include class definitions.

**Comment by dhylands** [comment]
The stuff where new is allocating something and the something isn't saved is for things like instantiating a new adapter. The adapter registers itself with the framework at an appropriate time (may be in the future after a bunch of async initialization is done).

**Pull request merged**
