### PR TITLE
Add French translation; Fix punctuation

### PR DESCRIPTION
**Pull request by gucci-on-fleek**
I've added a French translation for the WebThings Gateway. A few notes:
* I left the words "Gateway" and "Thing" untranslated because those appear to be a part of the branding. 
* In French, the translations for On/Off should be contextual. For example, the On/Off translation is different for a light bulb, a switch, and a plug. Currently, there is only one translation possible in the file.
* The translations for utils-XXX-ago don't really work. The proper translation would be in an infix-style ("Il y a # minutes") but the current format only allows for a postfix-style ("# minutes ago").
* My translation uses Canadian French. There are a  few slight vocabulary differences from France French, but it's all pretty minor.

I've also adjusted the punctuation in the English translation. I replaced the 3-period ellipsis (...) with the Unicode ellipsis (…). I also replaced space-hyphen-space ( - ) with thinspace-emdash-thinspace ( — ). I also removed the hyphen in "WiFi" because that appears to be more common (it's what Windows 10 uses) but the original "Wi-Fi" also appears to be correct. I personally prefer "WiFi" because I think that the hyphen is unnecessary, but I can switch it back to "Wi-Fi" if anyone disagrees.

### CODE REVIEW

**Comment by mrstegeman** [comment]
Thanks for doing this!

1. Please revert the Wi-Fi -> WiFi changes. Wi-Fi is the proper name.
2. What's your reason for switching to the Unicode ellipses?
3. There are some small UI changes we can make to allow for the infix-style formats for time stamps.

**Comment by benfrancis** [comment]
Thanks so much for this contribution!

>     1. Please revert the Wi-Fi -> WiFi changes. Wi-Fi is the proper name.

I agree, the [Wi-Fi alliance](https://www.wi-fi.org/) uses a hyphen.

>     2. What's your reason for switching to the Unicode ellipses?

Also curious what the reason is for replacing - with — ?

@lissyx I don't suppose you'd be willing to review this translation, or can recommend someone who can? (I realise this is like asking me to review an en-us translation...)

**Comment by lissyx** [comment]
Well I can review it, if it helps.

**Comment by lissyx** [comment]
@gucci-on-fleek can I ask you if you are french (FR) speaker or French (CA)? Your github profile shows Canada, and I know at least some punctuation rules do differ.

**Comment by lissyx** [comment]
Unicode ellipsis and dash uses are common throughout the French localization of mozilla product, BTW.

**Comment by lissyx** [comment]
OK, I saw that this is against fr-CA, do it's Canadian. @benfrancis, I don't know well the typographic and punctuation rules in this one. I can have a rough look but that may not be effective.

**Comment by gucci-on-fleek** [comment]
> Please revert the Wi-Fi -> WiFi changes  

Done.

> What's your reason for switching to the Unicode ellipses?

Spacing. The spacing between 3 periods and the Unicode ellipsis is slightly different. The Unicode ellipsis is slightly tighter than 3 periods, plus the appearance is as the font designer intended. Admittedly, the difference is minor.

> what the reason is for replacing - with —

A spaced hyphen ( - ) is, typographically speaking, always incorrect. There's the minus sign (−) for subtraction, the hyphen (-) for hyphenation,  the en-dash (–) for number ranges, and there's the em-dash (—) for parenthetical statements. Typically, the replacement for a spaced hyphen is an unspaced em-dash (—) or a spaced en-dash ( – ). Once again, it's a pretty minor difference.

> if you are french (FR) speaker or French (CA)

Canadian French. I went to school in French, but English is my first language, so there may be a few errors.

**Comment by mrstegeman** [comment]
@gucci-on-fleek Please see the following commits. You'll need to rebase after they're all merged, but I tried to adjust things to meet the needs of this (and other) translations. Please let me know if you think there are other things that should be fixed.

* ce7cb08caadae148ac7a9090da68e3b522d425d1
* fd1a0be59a3c8e760058a3aff84d652ab368fdb9
* #2283 
* #2284

**Comment by gucci-on-fleek** [comment]
Alright, hopefully I rebased that correctly… 
 
@mrstegeman Yep, those changes look good. I've updated the translation to use the CLDR plurals and I've added the Color Sensor translation.

One change that would improve the translation quality would be a contextualized on/off. In French, the state for a light is Lit/Unlit but the state for a switch is On/Off. (See [A](https://github.com/home-assistant/home-assistant-polymer/blob/ff7309f5c44e9e5e582c8b84df96305d43c5949e/translations/fr.json#L280), [B](https://github.com/home-assistant/home-assistant-polymer/blob/ff7309f5c44e9e5e582c8b84df96305d43c5949e/translations/fr.json#L299), [C](https://github.com/home-assistant/home-assistant-polymer/blob/ff7309f5c44e9e5e582c8b84df96305d43c5949e/translations/fr.json#L303), and [D](https://github.com/home-assistant/home-assistant-polymer/blob/ff7309f5c44e9e5e582c8b84df96305d43c5949e/translations/fr.json#L346) for 4 different translations) This might take a fair bit of refactoring to support this though, and it's really not much of a issue currently.

**Comment by mrstegeman** [comment]
@gucci-on-fleek I messed up rebasing some things, but this is now merged. Could you open one more PR and add a missing tag? `tunnel-setup-time-sync`

**Pull request closed without merging**
