### PR TITLE
install: Use sudo when needed in prepare-base-root.sh

### PR DESCRIPTION
**Pull request by rzr**
Change-Id: I4d6606897123d67e70299c0ce54949f58f59bd18
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>

### CODE REVIEW

**Comment by dhylands** [comment]
prepare-base-root.sh is already run under sudo from here:
https://github.com/mozilla-iot/gateway/blob/2acabaee1bb9dbb1f6d04026ba9ff9186d9dd9ea/image/prepare-base.sh#L140

**Comment by rzr** [comment]
True I didn't notice that, but anyway it is also using sudo in some parts, so I made it runable by user.

Actually both scripts could be merged, it's confusing...

**Comment by dhylands** [comment]
The intention was that prepare-base-root.sh would be run under sudo and not have to have sudo's all through it. If we sudo-ize it then there isn't any point in it being a separate script and it should be merged with prepare-base.sh

**Comment by rzr** [comment]
yea prepare-base.sh is using sudo already, but using sudo once has some advantages too, it will not ask password again on long operations.

**Comment by mrstegeman** [comment]
Replaced by #1179

**Pull request closed without merging**
