### PR TITLE
build: Transpile js for older webbrowsers

### PR DESCRIPTION
**Pull request by rzr**
Because of script failures, empty blue pages were displayed
(because some elements are still hidden).

Observed errors:

  W/ConsoleMessage( 3352): [ComExample] \
  webpack:///./static/js/authorize.js?:43: \
  Uncaught (in promise) ReferenceError: Utils is not defined

  Module build failed: \
  SyntaxError: 'import' and 'export' may only appear at the top level (22:4)

For the record some config info:

tizen-4.0-unified_20171027.1_mobile-wayland-armv7l-tm1

chromium-efl-56.2924.0.9-15.1.armv7l

Change-Id: If4a575a47d9c48d5f5d9b373a56c04df75c9814d
Signed-off-by: Philippe Coval <p.coval@samsung.com>

### CODE REVIEW

**Comment by rzr** [comment]
cc: @sogaani

**Comment by sogaani** [comment]
@rzr I'd say that `dynamic-import` is not a root cause.

> Observed errors:
> 
> W/ConsoleMessage( 3352): [ComExample]
> webpack:///./static/js/authorize.js?:43:
> Uncaught (in promise) ReferenceError: Utils is not defined

Because, `authorize.js` does not have any dynamic-import.

> Module build failed:
> SyntaxError: 'import' and 'export' may only appear at the top level (22:4)

How did you get this message? When build webpack? I want to reproduce this error.

> For the record some config info:
> 
> tizen-4.0-unified_20171027.1_mobile-wayland-armv7l-tm1
> 
> chromium-efl-56.2924.0.9-15.1.armv7l

Is this config about, a browser or a gateway?

**Comment by rzr** [comment]
webbrowser on tizen TM1 developer device:

https://wiki.tizen.org/TM1

**Comment by rzr** [comment]
The import rule is for generated bundle script once other javascripts are transpilated

If you want to repoduce maybe find an older distro shipping chromium-56, (or eventally try tizen SDK it ships a qemu image which similar version, I didn't try but it should be near the version I mentioned)

I also tried Midori-0.5.11 on WebKitGTK+ 2.4.9 (2.4.11) but more flags are needed I put some changes on hold.

**Comment by hobinjk** [comment]
I wasn't able to reproduce the import/export message on Chromium 56 (available for [mac](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Mac/433042/) or another OS by looking for a similar build number).

However, I am noticing that the Utils object appears to disappear between when it's required and when the init() function in authorize.js runs.

**Comment by hobinjk** [comment]
It looks like the only reason API is defined is that API.js includes the out-of-date line `window.API = API` which we shouldn't have in any case.

**Comment by sogaani** [comment]
I noticed that the following message will occur when add transpile rule with a babel-loader.
> Module build failed:
> SyntaxError: 'import' and 'export' may only appear at the top level (22:4)

```
    rules: [
      {
        test: /.\/static\/js\/.*\.js$/,
        use: [
          {
            loader: 'babel-loader',
          },
        ],
      },
```

This PR add dynamic-import-webpack plugin to avoid this errors.

**Comment by hobinjk** [comment]
Right, sorry for misunderstanding. This PR does fix the Utils undefined error and doesn't introduce the import/export error on my local setup.

This looks good to me for merging whenever, are there any concerns that I'm missing?

**Comment by sogaani** [comment]
If we will support older webbrowsers, we should take care about new ES functions, new ES grammars and new Browser features(e.g. websoket is not supported on IE9).
This PR maybe just take care new ES grammars. This is good first step.

If we will support new ES functions, we can use [`babel-polyfill`](https://babeljs.io/docs/usage/polyfill/), [`transform-runtime`](http://babeljs.io/docs/plugins/transform-runtime/) and [`babel-preset-env`](https://github.com/babel/babel/tree/master/packages/babel-preset-env).

**Comment by rzr** [comment]
"transform-es2015-arrow-functions", could help, I have also ongoing works but I gave up, maybe I will have a look later once this change is merged for my current configuration.

**Comment by sogaani** [comment]
@rzr 
Applying plugins for ES functions is maybe hard work, because we should check each ES functions supported on browser. Babel supports more easy way with `babel-preset-env` and `useBuiltIns` option.

I tried to support old browsers with  following codes.
Does following codes works on your browser?
```
yarn add @babel/polyfill @babel/core @babel/preset-env @babel/plugin-syntax-dynamic-import "babel-loader@^8.0.0-beta"
```

webpack.config.js
```
/**
 * Wepback configuration for the node server.
 */

const path = require('path');
const fs = require('fs');

const webpack = require('webpack');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const {CheckerPlugin} = require('awesome-typescript-loader');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const UglifyJsPlugin = require('uglifyjs-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CleanWebpackPlugin = require('clean-webpack-plugin');

const externals = {};
fs.readdirSync('node_modules')
  .filter(function(x) {
    return ['.bin'].indexOf(x) === -1;
  })
  .forEach(function(mod) {
    externals[mod] = `commonjs ${mod}`;
  });

const pluginsNode = [
  new CheckerPlugin(),
  new webpack.BannerPlugin({
    banner: 'require("source-map-support").install();',
    raw: true,
  }),
];

const webpackNode = {
  entry: './src/app.js',
  mode: 'development',
  target: 'node',
  node: {
    __dirname: false,
    __filename: false,
  },
  resolve: {
    extensions: ['.ts', '.js'],
  },
  output: {
    path: path.join(__dirname, 'build'),
    filename: 'gateway.js',
  },
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        loader: 'awesome-typescript-loader',
      },
    ],
  },
  devtool: 'sourcemap',
  plugins: pluginsNode,
  externals,
};

const pluginsWeb = [
  new CopyWebpackPlugin([
    {
      from: 'static/**/*',
      to: path.join(__dirname, 'build/'),
      ignore: ['*.js', '*/index.html'],
    },
    {
      from: 'static/js/lib/*',
      to: path.join(__dirname, 'build/'),
    },
    {
      from: 'static/service-worker.js',
      to: path.join(__dirname, 'build/static'),
    },
  ]),
  new UglifyJsPlugin({
    test: /\.js$/,
    sourceMap: true,
  }),
  new webpack.SourceMapDevToolPlugin({
    test: /\.css$/,
    filename: '[file].map',
  }),
  new MiniCssExtractPlugin({
    filename: 'bundle/[hash]-[name].css',
  }),
  new CleanWebpackPlugin(['build/static/bundle']),
  new HtmlWebpackPlugin({
    inject: 'head',
    template: 'static/index.html',
    chunks: ['style', 'app.js'],
  }),
  new HtmlWebpackPlugin({
    template: 'static/signup/index.html',
    filename: 'signup/index.html',
    chunks: ['create-user.js'],
  }),
  new HtmlWebpackPlugin({
    template: 'static/login/index.html',
    filename: 'login/index.html',
    chunks: ['login.js'],
  }),
  new HtmlWebpackPlugin({
    inject: 'head',
    template: 'src/views/authorize.mustache',
    filename: '../views/authorize.mustache',
    chunks: ['authorize.js'],
  }),
  new HtmlWebpackPlugin({
    inject: 'head',
    template: 'src/views/local-token-service.mustache',
    filename: '../views/local-token-service.mustache',
    chunks: ['check-user.js'],
  }),
  new HtmlWebpackPlugin({
    template: 'src/views/tunnel_setup.mustache',
    filename: '../views/tunnel_setup.mustache',
    chunks: ['setup_subdomain.js'],
  }),
];

const webpackWeb = {
  entry: {
    'app.js': ['./static/js/check-user.js', './static/js/app.js'],
    'create-user.js': ['./static/js/create-user.js'],
    'login.js': ['./static/js/check-user.js', './static/js/login.js'],
    'authorize.js': ['./static/js/check-user.js', './static/js/authorize.js'],
    'setup_subdomain.js': ['./static/js/setup_subdomain.js'],
    buildCss: [
      // css for static/index.html
      './static/css/app.css',
      './static/css/things.css',
      './static/css/menu.css',
      './static/css/add-thing.css',
      './static/css/context-menu.css',
      './static/css/thing.css',
      './static/css/floorplan.css',
      './static/css/settings.css',
      './static/css/rules-common.css',
      './static/css/rules.css',
      './static/css/rule.css',
      './static/css/addons-form.css',
    ],
  },
  mode: 'development',
  target: 'web',
  optimization: {
    splitChunks: {
      cacheGroups: {
        styles: {
          name: 'style',
          test: /\.css$/,
          chunks: 'all',
          enforce: true,
        },
      },
    },
  },
  output: {
    path: path.join(__dirname, 'build/static'),
    filename: 'bundle/[hash]-[name]',
    publicPath: '/',
  },
  module: {
    rules: [
      {
        test: /.\/static\/js\/.*\.js$/,
        use: [
          {
            loader: 'babel-loader',
            query: {
              babelrc: false,
              presets: [
                ['@babel/preset-env', {
                  targets: {
                    ie: 9,
                  },
                  useBuiltIns: 'usage',
                }],
              ],
              plugins: ['@babel/plugin-syntax-dynamic-import'],
            },
          },
        ],
      },
      {
        test: /\.css$/,
        use: [
          {
            loader: MiniCssExtractPlugin.loader,
          },
          {
            loader: 'css-loader',
            options: {
              sourceMap: true,
            },
          },
        ],
      },
      {
        test: /\.html$/,
        use: {
          loader: 'html-loader',
          options: {
            attrs: ['img:src'],
            root: path.join(__dirname, 'static'),
            minimize: true,
          },
        },
      },
      {
        test:
          /(?!\/uploads\/floorplan)\.(png|jpg|gif|svg|eot|ttf|woff|woff2)$/,
        use: [
          {
            loader: 'url-loader',
            options: {
              limit: 8000,
              fallback: 'file-loader',
              publicPath: '/images',
              outputPath: 'images',
            },
          },
        ],
      },
    ],
  },
  // When require stm_web.min.js, can't resolve 'fs'.
  // Maybe webpack bug.
  node: {
    fs: 'empty',
  },
  plugins: pluginsWeb,
  devtool: 'source-map',
};

module.exports = [
  webpackNode,
  webpackWeb,
];
```

If not works, you can change target browser to support more older browser.
see [API document](https://github.com/babel/babel/tree/master/packages/babel-preset-env#targets).
Furthermore, if Tizen browser does not support websocket, you need to add pollyfil for websocket.

```
                ['@babel/preset-env', {
                  targets: {
                    ie: 9, // here
                  },
                  useBuiltIns: 'usage',
                }],
```

**Comment by rzr** [comment]
Thanks @sogaani  this change is working too, so I updated this PR with your credited changes

For the record I tested on more recent versions:

    tizen-4.0-unified_20180118.1_mobile-wayland-armv7l-tm1
    chromium-efl-56.2924.0.9-24.9.armv7l

**Pull request merged**
