### PR TITLE
Update cross compile scripts

### PR DESCRIPTION
**Pull request by sogaani**
Now, we can not [build Raspberry Pi gateway on the host](https://github.com/mozilla-iot/wiki/wiki/Building-the-Raspberry-Pi-gateway-on-the-host), because installing [`pngquant-bin`](https://github.com/imagemin/pngquant-bin) dose not use node-gyp and environment variable to build from source.

This pull request propose that all process work with qemu-user to install node_modules.

Usage
```
sudo apt install docker.io apparmor apparmor-utils qemu-user-static wget

sudo docker run sdthirlwall/raspberry-pi-cross-compiler > ~/bin/rpxc
chmod +x ~/bin/rpxc

mkdir docker-moziot
cd docker-moziot
mkdir -p OpenZWave
cd OpenZWave
git clone https://github.com/OpenZWave/open-zwave.git
cd ..
git clone https://github.com/mozilla-iot/gateway

docker build -t your_image_name gateway/image/builder/
rpxc --image your_image_name gateway/image/build-gateway.sh
```

### CODE REVIEW

**Comment by sogaani** [comment]
@dhylands 
Thank you for giving about `rpi-image-builder`, I did not mind `rpi-image-builder`.
The `rpi-image-builder` dose not make the docker image to compile on arm emulator. 
I made changes on (`rpi-image-builder`)[https://github.com/sogaani/rpi-image-builder/tree/Rpxc_with_Dockerfile] in order to make and use a docker image.
I used the command:
```
./trigger-build.sh --repo https://github.com/sogaani/gateway --branch build-for-raspberry-pi --base gateway-bae-0.4.0.img --image gateway-0.4.0-soganni.img --brepo sogaani/rpi-image-builder --bbranch Rpxc_with_Dockerfile
```
We can see the build log here:
https://travis-ci.org/sogaani/rpi-image-builder/builds/375426059

However, above build still fail by an base-image size short.
```
...
tar: package/node_modules/number-is-nan/index.js: Cannot open: No such file or directory
tar: package/node_modules/number-is-nan: Cannot mkdir: No space left on device
tar: package/node_modules/number-is-nan/license: Cannot open: No such file or directory
tar: package/node_modules/number-is-nan: Cannot mkdir: No space left on device
...
```
Therefore, I made an [expanded base-image](https://drive.google.com/open?id=1yRTFzwYNUeLd7B96A4WdqiKZcAElqQ-G).
Could you upload to aws s3 in order to test?

In addition, I noticed that building gateway with arm-emulator is so slow on travis(take an hour).
I changed that `gateway-builder.sh` uses arm-emulator for the node_modules which we cannot cross compile.

**Comment by hobinjk** [comment]
If possible, I'd prefer to disable and remove image optimizations to the point where we can continue to build the gateway on the host. While we can always run pngquant and other optimizations by hand, we can't do anything about the complexity added by requiring pngquant at build-time.

**Comment by sogaani** [comment]
@hobinjk
I was thinking about [optimizations by hand](https://github.com/mozilla-iot/gateway/issues/943), and I prefer it than the build complexity too. So, I will remove optimizations and bundle the optimized images.

I will bundle the images not optimized in `static/image/***` and the images optimized in `static/optimized-image/***`, in order to be able retrying optimization.
However, I am wondering whether you prefer bundling the optimized images and not optimized.

**Comment by hobinjk** [comment]
@sogaani Yes, I agree. I think having `static/optimized-image/` with a script to regenerate is a great idea! It has the best of both worlds where we can still re-optimize images, but don't need to download every single image optimizer under the sun onto a raspberry pi.

**Comment by sogaani** [comment]
I create alternative pull request https://github.com/mozilla-iot/gateway/pull/986 and close this.

**Pull request closed without merging**
