### PR TITLE
Add Japanese (ja) localization

### PR DESCRIPTION
**Pull request by marsf**

### CODE REVIEW

**Comment by marsf** [comment]
This must be updated to follow  the en-US localization review #2326.

**Comment by mrstegeman** [comment]
@marsf Thank you for the translation!

1. Can you also update `static/js/fluent.js` with the new localization?
2. I've updated #2336 with another concatenation fix, to `add-things-add-adapters-hint`: https://github.com/mozilla-iot/gateway/pull/2336/files#diff-6c2b0a7209cee8fd4d75b53e3860b2faR233

**Comment by marsf** [comment]
@mrstegeman Updated.

**Comment by mrstegeman** [comment]
@marsf you can now find this project in Pontoon: https://pontoon.mozilla.org/projects/webthings-gateway/

**Pull request merged**
