### PR TITLE
Add --production to gateway build script

### PR DESCRIPTION
**Pull request by hobinjk**
Lets us actually take advantage of the benefits from splitting out dependencies and devDependencies. Reduces node_modules from 525M to 174M.

Will require a bunch of testing in 0.7 or 0.6.2

### CODE REVIEW

**Comment by mrstegeman** [comment]
Is this going to work? Right now, `run-app.sh` calls `npm start`, which in turn calls `webpack`. `webpack` is a dev dependency.

**Comment by hobinjk** [comment]
Oh right, I forgot that we pre-build everything. That will need a small update then (I think the ota script might also do a similar thing)

**Comment by hobinjk** [comment]
I believe this latest version should work as expected

**Comment by mrstegeman** [comment]
#1476 fixes the Travis errors

**Pull request merged**
