### PR TITLE
Add properly sized maskable icons

### LINKED ISSUE #2474: Maskable webmanifest icon
Please add the `"purpose":  "maskable" ` property to the icons in the webmanifest to enable maskable icons aka. adaptive icons on android.

### PR DESCRIPTION
**Pull request by lazylazyllama**
Fixes #2474

### CODE REVIEW

**Comment by benfrancis** [comment]
Nit: These icons are not as high quality as the originals. @lazylazyllama How did you generate them? Would you like me to generate some new ones from the SVG source? (We could also add an SVG icon with a size of "any").

**Comment by lazylazyllama** [comment]
> Nit: These icons are not as high quality as the originals. @lazylazyllama How did you generate them? Would you like me to generate some new ones from the SVG source? (We could also add an SVG icon with a size of "any").

I see your point I will create some new ones with inkscape then and also add a svg :)

**Comment by benfrancis** [comment]
@lazylazyllama No need to create a new one, here is the original SVG https://drive.google.com/file/d/1MLENWcjol2WS5YGRNV8elda5fjIlxGN9/view?usp=sharing

**Comment by lazylazyllama** [comment]
> @lazylazyllama No need to create a new one, here is the original SVG https://drive.google.com/file/d/1MLENWcjol2WS5YGRNV8elda5fjIlxGN9/view?usp=sharing

Thank you, sorry for confusing you, what I meant is that I change it to a new one with properly padding around so that it can be used as a maskable icon just like the new ones etc.

**Comment by lazylazyllama** [comment]
@benfrancis I added your icons + the new maskable files in #2578

**Pull request merged**
