### PR TITLE
Test Rules Engine's rule execution

### PR DESCRIPTION
**Pull request by hobinjk**
This takes advantage of the fact that the rules engine is part of the gateway to perform a complete test of its rule execution. Notably this also solves an intermittent issue where `storage.init` calls in tests could race and make everything sad.

### CODE REVIEW

**Comment by dhylands** [comment]
Admittedly, I didn't try this to perform an update.

**Comment by hobinjk** [comment]
Thanks for reviewing! The way I understand async/await is that `async` means a function can use `await` and will return a promise. `await` then runs the promise to completion and returns whatever it resolves to.

```javascript
async function doThing() {
  let stuff = await thing();
  return await otherThing(stuff);
}
```
is equivalent to
```javascript
function doThing() {
  return thing().then(stuff => {
    return otherThing(stuff);
  });
}
```

**Comment by hobinjk** [comment]
@dhylands I think that second comment is for #283 ?

**Comment by dhylands** [comment]
Doh - yeah (second comment was for #283)

**Pull request merged**
