### PR TITLE
Implementing redirection from http to https when accessing by the tunnel

### PR DESCRIPTION
**Pull request by andrenatal**

### CODE REVIEW

**Comment by andrenatal** [comment]
Fixes #319

**Comment by hobinjk** [comment]
These changes do cause gateways at 0.2.0 and below to fail to register via LE which I think is just something we need to keep in mind

**Comment by andrenatal** [comment]
BTW, now we have `mozilla-iot-staging.org` running as staging. You can use it to dev/test to avoid keep creating production certs on prod, for example.

**Comment by andrenatal** [comment]
@hobinjk I'll revert this PR since the nginx approached worked better and we don't need pagekite for port 80 anymore

**Pull request merged**
