### PR TITLE
v0.6.1 Candidates

### PR DESCRIPTION
**Pull request by mrstegeman**

### CODE REVIEW

**Comment by mrstegeman** [comment]
Not entirely sure why Travis CI is failing, `npm run test` works for me locally.

**Comment by hobinjk** [comment]
Looks like every test that uses the browser is failing with a timeout or "A session id is required for this command but wasn't found in the response payload". This is likely related to the new Firefox release

**Comment by mrstegeman** [comment]
Yep, I just realized the same thing. Working on a fix.

**Comment by mrstegeman** [comment]
I thought that upgrading `webdriverio` and/or `selenium-standalone` would fix it, but apparently not.

**Pull request merged**
