### PR TITLE
Add a route to allow user to download logs.

### PR DESCRIPTION
**Pull request by mrstegeman**
References #645

### CODE REVIEW

**Comment by benfrancis** [comment]
A couple of thoughts:
* What should be the relationship between /debug and /logs? We already have a debug controller which is useful for development but I think has to be enabled with a command line argument. Is this more of a user-facing thing?
* Is creating a .zip file the best approach? I wonder if might be nicer to just view the logs in my browser. If there are multiple log files the /logs could be an index with links to /logs/foo and /logs/bar.

**Comment by mrstegeman** [comment]
1. `/debug` is only allowed if node's `debug` option is set. `/logs` should probably always be available.
2. That's probably doable, but will be a larger amount of effort for what is really a developer feature. Also, you told me you didn't think it should be exposed through the UI :-) (https://github.com/mozilla-iot/gateway/issues/645#issuecomment-367669503). There are indeed multiple log files. Right now, there's `run-app.log` plus the Z-Wave logs, but there could eventually be a lot more.

Maybe for 0.4, we can put a link somewhere in the UI that will allow the user to at least download the zip file. After 0.4, we could consider adding a log-reader UI.

**Comment by benfrancis** [comment]
I didn't mean a log-reader UI necessarily, just that loading /logs in the browser would provide a plain text response which the browser can render, rather than having to download and unzip a file and open the file you wanted.

Is that not possible because of a missing JWT or something?

**Comment by mrstegeman** [comment]
Correct, you'd be missing the JWT. I believe we have support for parsing the JWT out of a URL param, but we have to get it there somehow initially, i.e. via a link from the UI.

**Comment by mrstegeman** [comment]
@benfrancis I will add some additional routes to do a directory listing and allow the user to view an individual file in the browser. Then we can decide what we actually want to make available from the UI (and where).

**Pull request merged**
