### PR TITLE
experimental... add a little life to the 🦊 

### PR DESCRIPTION
**Pull request by autonome**
Hacked in a little experiment to add a little playfulness to the assistant:

* Head follows mouse around
* Tail swishes every 10s

Not polished, definitely needs a lot of work, but thought it would would be fun!

🦊 🦊 🦊 🦊 🦊 🦊 🦊 🦊 🦊 🦊 🦊 🦊

### CODE REVIEW

**Comment by autonome** [comment]
fox

**Comment by benfrancis** [comment]
Haha, thanks Dietrich. This is very cute :P See also https://github.com/mozilla-iot/gateway/issues/1159

**Comment by autonome** [comment]
Haha I'm glad we are of the same mind on this important issue 😂

**Comment by jaller94** [comment]
This is awesome. I enjoy the addition of the avatar and bringing life to it.

I wish the animations were smoother. The head could have a little delayed, faded head movement.
The tail twich is a great idea, however, the current implementation looks extreme and unnatural to me. I wish it was more subtle with less triangles of the tail moving and the animation being slower. The movement of the fox should not be distracting but make it look alive.

Thank you for taking the time and knowledge to build this.

**Comment by autonome** [comment]
Hi @jaller94! Yeah this was just me being bored one night and wanting to learn some SVG animation stuff, definitely not a candidate for release ;)

More just to get people thinking about what's possible!

**Pull request closed without merging**
