### PR TITLE
Support node 10

### LINKED ISSUE #1120: Deal with the existence of Node 10
- [ ] Fix dependencies that break under node 10
- [ ] Pin nvm to install node 8
- [ ] Run tests on node 10

### PR DESCRIPTION
**Pull request by hobinjk**
Fix #1120

### CODE REVIEW

**Comment by hobinjk** [comment]
This also increases the impact of intermittent travis failures by around 50% which is unfortunate

**Comment by mrstegeman** [comment]
@hobinjk Is the `yarn.lock` change due to running `yarn update`?

**Comment by dhylands** [comment]
It would be good to figure out whats causing the travis failures before merging this.

**Comment by hobinjk** [comment]
Yes, I ran `yarn upgrade` which upgraded far more dependencies than I intended and broke travis

**Comment by dhylands** [comment]
> Yes, I ran yarn upgrade which upgraded far more dependencies than I intended and broke travis

Do we need a separate yarn.lock for node 8 versus node 10?

**Comment by mrstegeman** [comment]
Travis CI also failed while running with node 10, so I don't think so.

**Comment by mrstegeman** [comment]
I'd like to note that some of our add-ons (probably) will not work with node 10 right now.

**Comment by hobinjk** [comment]
No compiled addons will work with node 10 since its NODE_MODULE_VERSION is different. `thing-url-adapter` and `zwave-adapter` were the only adapters I saw with other incompatibilities (which `yarn upgrade` fixed)

**Comment by dhylands** [comment]
I think that just means that we need to build 2 different flavors of the addons and add the NODE_MODULE_VERSION into the list.json file.

**Comment by mrstegeman** [comment]
Yeah, we'll definitely have to put the node version in `list.json`. Let's do that for 0.6, as it's going to be a pretty large change again.

**Comment by hobinjk** [comment]
:+1:

**Comment by mrstegeman** [comment]
I've filed #1122 for the add-ons.

**Pull request merged**
