### PR TITLE
Refresh add-on list on entering add-on settings.

### PR DESCRIPTION
**Pull request by mrstegeman**

### CODE REVIEW

**Comment by mrstegeman** [comment]
That's a good question. It used to be refreshed every time the list was shown. However, it's now cached and is only fetched once while the things UI is open. We could either do it this way or revert to the old behavior.

**Comment by dhylands** [comment]
Is it possible to create a list hash and retrieve that every time and only update the list when the hash changes?

**Comment by mrstegeman** [comment]
Yes, that's another option as well.

**Comment by mrstegeman** [comment]
@hobinjk I changed the commit to essentially revert to old behavior. The add-on list is always updated when the user enters _Settings->Add-ons_, and updated only if necessary when going into an add-on config screen or the discovered add-ons screen, i.e. if they navigate directly there in a new tab for some reason.

**Pull request merged**
