### PR TITLE
Dimmable Color Light UI

### PR DESCRIPTION
**Pull request by hobinjk**
Incorporates #501

### CODE REVIEW

**Comment by hobinjk** [comment]
(updated to incorporate reviews of #492 and #501)

**Comment by benfrancis** [comment]
@hobinjk Any chance of adding a dimmableColorLight to the Virtual Things adapter so I can see this in action? Also comments from onOffColorLight and multiLevelSwitch obviously apply here too.

**Comment by hobinjk** [comment]
Oh woops, I had a dCL added locally but forgot to push to the remote. It should now exist for you too.

**Comment by mrstegeman** [comment]
Fixes #510

**Pull request merged**
